export const generateBasicMockData = () => {
  return [
    {
      id: Date.now() + 1,
      name: 'Lait',
      category: 'produits laitiers',
      zone: 'Étagère haute',
      quantity: 1,
      confidence: 0.95,
      suggestedExpiryDate: new Date(Date.now() + 7 * 24 * 60 * 60 * 1000).toISOString().split('T')[0],
      confirmed: true,
    },
    {
      id: Date.now() + 2,
      name: 'Poulet',
      category: 'viandes',
      zone: 'Étagère basse (zone froide)',
      quantity: 1,
      confidence: 0.89,
      suggestedExpiryDate: new Date(Date.now() + 3 * 24 * 60 * 60 * 1000).toISOString().split('T')[0],
      confirmed: true,
    },
    {
      id: Date.now() + 3,
      name: 'Tomates',
      category: 'légumes',
      zone: 'Bac à légumes',
      quantity: 5,
      confidence: 0.92,
      suggestedExpiryDate: new Date(Date.now() + 10 * 24 * 60 * 60 * 1000).toISOString().split('T')[0],
      confirmed: true,
    },
    {
      id: Date.now() + 4,
      name: 'Fromage',
      category: 'produits laitiers',
      zone: 'Étagère haute',
      quantity: 1,
      confidence: 0.88,
      suggestedExpiryDate: new Date(Date.now() + 14 * 24 * 60 * 60 * 1000).toISOString().split('T')[0],
      confirmed: true,
    },
    {
      id: Date.now() + 5,
      name: 'Jus d\'orange',
      category: 'boissons',
      zone: 'Porte du frigo',
      quantity: 1,
      confidence: 0.91,
      suggestedExpiryDate: new Date(Date.now() + 5 * 24 * 60 * 60 * 1000).toISOString().split('T')[0],
      confirmed: true,
    },
  ];
};

export const generateLargeMockData = () => {
  return [
    ...generateBasicMockData(),
    {
      id: Date.now() + 6,
      name: 'Saumon frais',
      category: 'poissons',
      zone: 'Étagère basse (zone froide)',
      quantity: 2,
      confidence: 0.87,
      suggestedExpiryDate: new Date(Date.now() + 2 * 24 * 60 * 60 * 1000).toISOString().split('T')[0],
      confirmed: true,
    },
    {
      id: Date.now() + 7,
      name: 'Carottes bio',
      category: 'légumes',
      zone: 'Bac à légumes',
      quantity: 1,
      confidence: 0.94,
      suggestedExpiryDate: new Date(Date.now() + 10 * 24 * 60 * 60 * 1000).toISOString().split('T')[0],
      confirmed: true,
    },
    {
      id: Date.now() + 8,
      name: 'Yaourt nature',
      category: 'produits laitiers',
      zone: 'Étagère haute',
      quantity: 8,
      confidence: 0.93,
      suggestedExpiryDate: new Date(Date.now() + 7 * 24 * 60 * 60 * 1000).toISOString().split('T')[0],
      confirmed: true,
    },
    {
      id: Date.now() + 9,
      name: 'Œufs',
      category: 'produits laitiers',
      zone: 'Porte du frigo',
      quantity: 6,
      confidence: 0.96,
      suggestedExpiryDate: new Date(Date.now() + 21 * 24 * 60 * 60 * 1000).toISOString().split('T')[0],
      confirmed: true,
    },
    {
      id: Date.now() + 10,
      name: 'Beurre doux',
      category: 'produits laitiers',
      zone: 'Porte du frigo',
      quantity: 1,
      confidence: 0.90,
      suggestedExpiryDate: new Date(Date.now() + 30 * 24 * 60 * 60 * 1000).toISOString().split('T')[0],
      confirmed: true,
    },
  ];
};

export const generateExpiringMockData = () => {
  return [
    {
      id: Date.now() + 1,
      name: 'Lait (expire demain)',
      category: 'produits laitiers',
      zone: 'Étagère haute',
      quantity: 1,
      confidence: 0.95,
      suggestedExpiryDate: new Date(Date.now() + 1 * 24 * 60 * 60 * 1000).toISOString().split('T')[0],
      confirmed: true,
    },
    {
      id: Date.now() + 2,
      name: 'Yaourt (expire dans 2 jours)',
      category: 'produits laitiers',
      zone: 'Étagère haute',
      quantity: 4,
      confidence: 0.92,
      suggestedExpiryDate: new Date(Date.now() + 2 * 24 * 60 * 60 * 1000).toISOString().split('T')[0],
      confirmed: true,
    },
    {
      id: Date.now() + 3,
      name: 'Viande hachée (URGENT)',
      category: 'viandes',
      zone: 'Étagère basse',
      quantity: 1,
      confidence: 0.89,
      suggestedExpiryDate: new Date(Date.now() + 1 * 24 * 60 * 60 * 1000).toISOString().split('T')[0],
      confirmed: true,
    },
  ];
};